#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
merge_toc.py — 充填済み pending を統合し toc.yaml を書き出す（doc-advisor plugin / key + path I/F）

DES-005 §6.1（prepare/merge 2 フェーズ）/ §6.2（差分検出）/ §6.3（破壊性）/
§6.5（バックアップと異常系: backup → validate → restore）/ §6.6（continuation）/
§7.1（toc.yaml スキーマ: doc_type なし）/ §7.2（metadata.key 転記）/ §8（JSON 契約）/
§4.1（モジュール）を実装する。DES-005 §6.5 の挙動を key 単位ストアで踏襲する。

責務（決定的処理。メタデータ抽出はしない / FR-N07-1）:
- key 解決（toc_store.resolve_key_from_args。--all / --key 省略 → 予約 all、--key all → reject）
- store_dir/.toc_work/ の充填済み pending（status: completed）を既存 toc.yaml の docs とマージ
- desired-state の deleted（prepare 算出 / checksums と現状の差）を toc.yaml から除去（FR-N02-2）
- backup → 原子的書き込み → validate → OK で checksums 更新 + work 削除 / NG で復元（§6.5）
- --key 引数の値を toc.yaml の metadata.key へ書き出す（§7.2）
- added/updated/deleted/unchanged 件数と deleted paths を JSON 出力（FR-N02-4 / FR-N08）
- AI 抽出だった対象（pending の `_meta.extracted_by: ai`）を `ai_extracted_paths` として
  成功時の JSON へ集約（DES-008 §8.2 の書き戻し候補。報告用の出力のみで toc.yaml には出さない）

CLI:
    python3 merge_toc.py --key <key>
    python3 merge_toc.py --all
    python3 merge_toc.py --key <key> --delete-only

標準ライブラリのみ使用（NFR-N01）。
"""

import argparse
import json
import os
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from toc_utils import (
    get_project_root,
    normalize_path,
    yaml_escape,
    load_entry_file,
    load_existing_toc,
    load_checksums,
    calculate_file_hash,
    write_checksums_yaml,
    log,
)
from toc_store import (
    WORK_DIRNAME,
    CHECKSUMS_FILENAME,
    DELETED_SIDECAR_FILENAME,
    EMPTY_INTENT_SIDECAR_FILENAME,
    ErrorCode,
    KeyError_,
    STATUS_OK,
    STATUS_ERROR,
    TOC_FILENAME,
    resolve_store_dir,
    resolve_key_from_args,
    emit_json,
    toc_path_rel,
    clean_work_dir,
)
from validate_toc import validate_toc

# ---------------------------------------------------------------------------
# 定数
# ---------------------------------------------------------------------------

# backup ファイル名（§6.5: toc.yaml.bak）
BACKUP_SUFFIX = ".bak"

# ToC エントリのスカラ / 配列フィールド描画順（DES-005 §7.1: doc_type なし）
SCALAR_FIELDS = ("title", "purpose")
LIST_FIELDS = ("content_details", "applicable_tasks", "keywords")

# pending の `_meta.extracted_by` が AI 抽出由来を示す値（DES-008 §8.2）。
# `write_pending.py` が書き込む値と一致させる。転記由来（`frontmatter`）や
# 値を持たない pending（既存持ち越し等）は集約に含めない。
EXTRACTED_BY_AI = "ai"


# ---------------------------------------------------------------------------
# toc.yaml 書き出し（DES-005 §7.1 / §7.2 / §6.5 原子的書き込み）
# ---------------------------------------------------------------------------

def render_toc_yaml(docs, *, key, toc_rel):
    """docs を toc.yaml の文字列として描画する（DES-005 §7.1 / §7.2）。

    docs 順序は **path のソート順** で決定的に出力する（FR-N05-2 整合）。
    get_toc は toc.yaml の定義順をそのまま保持するため、ここでの出力順が
    そのまま検索結果順になる。再現可能な順序として path 昇順を採用する。

    metadata は name / key / generated_at / file_count（§7.1 スキーマ、doc_type なし）。
    metadata.key には --key 引数の値を書き出す（§7.2）。

    Args:
        docs: source_file -> entry の dict
        key: original key（metadata.key / metadata.name 由来）
        toc_rel: toc.yaml の project-relative パス（ヘッダ表示用）

    Returns:
        str: toc.yaml の本文（末尾改行付き）
    """
    lines = []
    lines.append(f"# {toc_rel}")
    lines.append(f"# Document Search Index for key: {key}")
    lines.append("# Auto-generated by doc-advisor index-docs - Do not edit directly")
    lines.append("")

    lines.append("metadata:")
    lines.append(f"  name: {yaml_escape(f'Document Search Index ({key})')}")
    lines.append(f"  key: {yaml_escape(key)}")
    lines.append(
        f"  generated_at: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}"
    )
    lines.append(f"  file_count: {len(docs)}")
    lines.append("")

    lines.append("docs:")
    for source_file in sorted(docs.keys()):
        entry = docs[source_file]
        lines.append(f"  {yaml_escape(source_file)}:")
        for field in SCALAR_FIELDS:
            if field in entry and entry[field] is not None:
                lines.append(f"    {field}: {yaml_escape(entry[field])}")
        for field in LIST_FIELDS:
            if field in entry and entry[field]:
                lines.append(f"    {field}:")
                for item in entry[field]:
                    lines.append(f"      - {yaml_escape(item)}")

    return "\n".join(lines) + "\n"


def write_toc_atomic(docs, toc_path, *, key, toc_rel):
    """toc.yaml を原子的に書き出す（DES-005 §6.5 / 旧 write_yaml_output の os.replace 流用）。

    一時ファイルへ書き込んでから os.replace で置換し、書き込み途中の破損を防ぐ。

    Args:
        docs: source_file -> entry の dict
        toc_path: 出力先 toc.yaml の Path
        key: original key（metadata 用）
        toc_rel: toc.yaml の project-relative パス（ヘッダ用）

    Returns:
        bool: True on success, False on failure
    """
    body = render_toc_yaml(docs, key=key, toc_rel=toc_rel)
    toc_path = Path(toc_path)
    try:
        output_dir = toc_path.parent
        output_dir.mkdir(parents=True, exist_ok=True)
        fd, tmp_path = tempfile.mkstemp(dir=str(output_dir), suffix=".tmp", prefix=".toc_")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(body)
            os.replace(tmp_path, str(toc_path))
        except BaseException:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass
            raise
        return True
    except (IOError, OSError, PermissionError) as e:
        log(f"Error: Failed to write toc.yaml: {toc_path} - {e}")
        return False


# ---------------------------------------------------------------------------
# pending 統合（DES-005 §6.1）
# ---------------------------------------------------------------------------

def load_completed_pendings(work_dir):
    """work_dir 配下の pending YAML を読み、status: completed のみ抽出する。

    entries の意味は従来どおり（completed な pending の source_file -> entry）。
    加えて `_meta.extracted_by`（DES-008 §8.2 の来歴。`frontmatter` | `ai`）を
    provenance として返す。報告用の情報であり toc.yaml の内容には影響しない。

    Args:
        work_dir: store_dir/.toc_work/ の Path

    Returns:
        tuple: (entries, provenance, errors)
            entries: source_file -> entry の dict（completed のみ）
            provenance: source_file -> extracted_by 値（欠落時は None）の dict
            errors: 警告メッセージのリスト（source_file 欠落 / 未完了 等）
    """
    entries = {}
    provenance = {}
    errors = []

    work_dir = Path(work_dir)
    if not work_dir.exists():
        return entries, provenance, errors

    # 隠しファイル（.toc_checksums_pending.yaml 等）を除外し、決定的順序で処理
    yaml_files = sorted(
        f for f in work_dir.glob("*.yaml") if not f.name.startswith(".")
    )

    for filepath in yaml_files:
        filename = filepath.name
        try:
            meta, entry = load_entry_file(filepath)
        except IOError as e:
            errors.append(f"{filename}: {e}")
            continue

        source_file = meta.get("source_file")
        status = meta.get("status")

        if not source_file:
            errors.append(f"{filename}: missing _meta.source_file")
            continue
        if status != "completed":
            errors.append(f"{filename}: status is not completed ({status})")
            continue

        normalized = normalize_path(source_file)
        entries[normalized] = entry
        provenance[normalized] = meta.get("extracted_by")

    return entries, provenance, errors


# ---------------------------------------------------------------------------
# 削除検出（DES-005 §6.2 / FR-N02-2）
# ---------------------------------------------------------------------------

def load_deleted_sidecar(work_dir):
    """prepare が残した deleted サイドカー（.deleted.json）を読む（DES-005 §6.1 / §6.2）。

    prepare は `deleted = prev.keys() - desired` を算出し、本サイドカーへ JSON 配列で
    書き出す。merge はこれを desired-state の削除の正として反映する（FR-N02-2）。
    ファイルが存在しない場合は空リストを返す。

    Args:
        work_dir: store_dir/.toc_work/ の Path

    Returns:
        list[str]: 削除対象 path（正規化済み）
    """
    sidecar = Path(work_dir) / DELETED_SIDECAR_FILENAME
    if not sidecar.exists():
        return []
    try:
        data = json.loads(sidecar.read_text(encoding="utf-8"))
    except (IOError, OSError, PermissionError, ValueError) as e:
        log(f"Warning: Failed to read deleted sidecar: {sidecar} - {e}")
        return []
    if not isinstance(data, list):
        return []
    return [normalize_path(p) for p in data if isinstance(p, str)]


def detect_deleted(docs, prev_checksums, sidecar_deleted, project_root):
    """toc.yaml から除去すべき path を算出する（DES-005 §6.2 / FR-N02-2）。

    desired-state モデルの削除は 2 つの源から決まる:
      1. prepare が算出し `.deleted.json` サイドカーへ残した deleted
         （= 前回 checksums にあり今回 desired に含まれない path。実ファイルが
           存在していても desired から外れたものを含む。「部分配列 → 残り削除」を支える）
      2. 実ファイルが存在しない path（checksums または toc.yaml に残る stale エントリ）。
         サイドカーが無い `--delete-only` フォールバック経路でも削除を成立させる

    Args:
        docs: 現在の toc.yaml docs（source_file -> entry）
        prev_checksums: 前回 checksums（path -> hash）
        sidecar_deleted: prepare のサイドカーから読んだ deleted（正規化済み path リスト）
        project_root: project root（Path）

    Returns:
        list[str]: 削除対象 path（昇順）
    """
    root = Path(project_root)
    deleted = set(sidecar_deleted)

    # 実ファイル不在の stale（checksums / toc.yaml 双方を見る）
    for path in list(prev_checksums.keys()) + list(docs.keys()):
        full = root / path
        if not full.exists():
            deleted.add(normalize_path(path))

    return sorted(deleted)


# ---------------------------------------------------------------------------
# checksums 再計算（DES-005 §6.2 / FR-N02-6）
# ---------------------------------------------------------------------------

def compute_checksums_for_docs(docs, project_root, completed_paths=None, prev_checksums=None):
    """toc.yaml の最終 docs から checksums（path -> hash）を再計算する。

    **重要（Issue #22 レビュー対応）**: 今回の run で実際に充填された（completed）doc のみ
    現内容ハッシュを書く。それ以外（既存からの持ち越し entry）は **前回 checksum を引き継ぐ**。
    こうしないと、改訂されたが充填に失敗した updated doc に対し「現内容ハッシュ」を書いてしまい、
    次回 prepare が「変更なし」と誤判定して**改訂が二度と索引されない（stale 固定）**。
    持ち越し doc に前回値を残せば、現内容と差が出る限り次回 prepare が「updated」と検知して再充填する。

    - completed_paths に含まれる path → 現内容の sha256（充填済み＝entry は現内容由来）
    - それ以外で prev_checksums に値あり → 前回値を引き継ぐ（unchanged は現内容と同値、
      errored-updated は旧値が残り次回再検知される）
    - どちらでもない（前回値なしの持ち越し。通常起きない）→ フォールバックで現内容ハッシュ

    実体が読めない path は除外する（検証で別途検出される）。

    Args:
        docs: 最終 docs（source_file -> entry）
        project_root: project root（Path）
        completed_paths: 今回 run で充填された path の集合（None 互換: 全て現内容ハッシュ＝旧挙動）
        prev_checksums: 前回 checksums（path -> hash）。持ち越し doc の引き継ぎ元

    Returns:
        dict: path -> sha256 hash
    """
    root = Path(project_root)
    completed_paths = set(completed_paths) if completed_paths is not None else None
    prev_checksums = prev_checksums or {}
    checksums = {}
    for path in docs.keys():
        if completed_paths is None or path in completed_paths:
            # 充填済み（または旧 API 互換）→ 現内容ハッシュ
            h = calculate_file_hash(root / path)
        else:
            # 持ち越し entry → 前回値を引き継ぐ（現内容を「索引済み」と詐称しない）
            h = prev_checksums.get(path)
            if h is None:
                h = calculate_file_hash(root / path)
        if h is not None:
            checksums[path] = h
    return checksums


# ---------------------------------------------------------------------------
# backup / restore（DES-005 §6.5）
# ---------------------------------------------------------------------------

def backup_toc(toc_path):
    """toc.yaml を toc.yaml.bak へバックアップする（§6.5）。

    既存 toc.yaml が無い場合は何もしない（新規生成）。

    Args:
        toc_path: toc.yaml の Path

    Returns:
        Path | None: バックアップファイルの Path（作成した場合）、無ければ None
    """
    toc_path = Path(toc_path)
    if not toc_path.exists():
        return None
    backup_path = toc_path.with_name(toc_path.name + BACKUP_SUFFIX)
    try:
        backup_path.write_bytes(toc_path.read_bytes())
        log(f"Backup created: {backup_path}")
        return backup_path
    except (IOError, OSError, PermissionError) as e:
        log(f"Warning: Failed to create backup: {backup_path} - {e}")
        return None


def restore_toc(toc_path, backup_path):
    """toc.yaml.bak から toc.yaml を復元する（§6.5 検証失敗時）。

    backup が無い場合（新規生成で検証失敗）は、書き出した toc.yaml を削除して
    元の「不在」状態へ戻す。

    Args:
        toc_path: toc.yaml の Path
        backup_path: バックアップファイルの Path（None の場合は新規生成だった）

    Returns:
        bool: True on success
    """
    toc_path = Path(toc_path)
    if backup_path is not None and Path(backup_path).exists():
        try:
            toc_path.write_bytes(Path(backup_path).read_bytes())
            log(f"Restored from backup: {backup_path} -> {toc_path}")
            return True
        except (IOError, OSError, PermissionError) as e:
            log(f"Error: Failed to restore from backup: {e}")
            return False
    # backup なし = 新規生成だった。検証失敗した toc.yaml を消して不在へ戻す。
    try:
        if toc_path.exists():
            toc_path.unlink()
            log(f"Removed invalid newly-generated toc.yaml: {toc_path}")
        return True
    except (OSError, PermissionError) as e:
        log(f"Error: Failed to remove invalid toc.yaml: {e}")
        return False


def remove_backup(backup_path):
    """検証成功後にバックアップファイルを削除する（残骸を残さない）。"""
    if backup_path is None:
        return
    try:
        bp = Path(backup_path)
        if bp.exists():
            bp.unlink()
    except (OSError, PermissionError) as e:
        log(f"Warning: Failed to remove backup: {backup_path} - {e}")


# ---------------------------------------------------------------------------
# merge コア（DES-005 §6.1 / §6.5）
# ---------------------------------------------------------------------------

def run_merge(store_dir, key, project_root, *, delete_only=False):
    """pending 統合 + 削除反映 + backup → validate → restore を実行する。

    Args:
        store_dir: store_dir の Path
        key: original key
        project_root: project root（Path）
        delete_only: True のとき pending を統合せず削除のみ反映する

    Returns:
        tuple: (ok, payload_kwargs)
            ok: True on success
            payload_kwargs: emit_json に渡す追加 kwargs（counts / warnings 等）。
                成功時のみ `ai_extracted_paths`（AI 抽出だった対象の一覧。
                DES-008 §8.2 の書き戻し候補）を含む。ToC の生成が完了して
                いない経路（書き込み失敗・validation 失敗で `.toc_work/` を
                保持する経路）では提示しないため出力しない
    """
    store_dir = Path(store_dir)
    toc_path = store_dir / TOC_FILENAME
    toc_rel = toc_path_rel(store_dir, project_root)
    work_dir = store_dir / WORK_DIRNAME
    checksums_file = store_dir / CHECKSUMS_FILENAME

    warnings = []

    # 既存 toc.yaml の docs（incremental ベース）
    existing_docs = load_existing_toc(toc_path) if toc_path.exists() else {}
    prev_checksums = load_checksums(checksums_file)
    prev_doc_paths = set(existing_docs.keys())

    # 1. pending 統合（delete-only では行わない）
    completed = {}
    provenance = {}
    if not delete_only:
        completed, provenance, merge_errors = load_completed_pendings(work_dir)
        warnings.extend(merge_errors)

    # 2. docs を構築（既存 + pending 上書き）。
    #    added/updated は prev_checksums 基準で判定する（§6.2 と一貫）。
    #    pending は prepare が added/updated と確定したものだけが入る。
    docs = dict(existing_docs)
    added = []
    updated = []
    for source_file, entry in completed.items():
        if source_file in prev_checksums:
            updated.append(source_file)
        else:
            added.append(source_file)
        docs[source_file] = entry

    # 3. 削除反映（FR-N02-2）。prepare のサイドカー + 実体不在 stale。
    sidecar_deleted = load_deleted_sidecar(work_dir)
    deleted = detect_deleted(docs, prev_checksums, sidecar_deleted, project_root)
    for del_path in deleted:
        if del_path in docs:
            del docs[del_path]
            log(f"  Deleted: {del_path}")

    # unchanged: 前回 toc にあり、added/updated/deleted のいずれでもないもの
    changed_set = set(added) | set(updated) | set(deleted)
    unchanged = sorted(p for p in prev_doc_paths if p not in changed_set and p in docs)

    counts = {
        "added": len(added),
        "updated": len(updated),
        "deleted": len(deleted),
        "unchanged": len(unchanged),
    }

    # 4. backup → 原子的書き込み → validate → restore（§6.5）
    backup_path = backup_toc(toc_path)

    if not write_toc_atomic(docs, toc_path, key=key, toc_rel=toc_rel):
        # 書き込み自体が失敗。backup から復元。
        restore_toc(toc_path, backup_path)
        return False, {
            "error_code": ErrorCode.NOT_FOUND,
            "message": "failed to write toc.yaml",
            "counts": counts,
            "deleted_paths": deleted,
            "warnings": warnings,
        }

    # 検証（空 ToC は検証をスキップして冪等に成功させる / §9.2 空 ToC 冪等出力）
    validation_ok = True
    if docs:
        validation_ok = validate_toc(toc_path, project_root=project_root)

    if not validation_ok:
        # §6.5 NG: backup から復元・checksums 据え置き・.toc_work 保持
        restore_toc(toc_path, backup_path)
        log("Validation failed: toc.yaml restored, checksums kept, .toc_work preserved")
        return False, {
            "error_code": ErrorCode.INVALID_PATH,
            "message": "validation failed; toc.yaml restored from backup, "
                       ".toc_work preserved for retry",
            "counts": counts,
            "deleted_paths": deleted,
            "warnings": warnings,
        }

    # 5. OK: checksums 更新（§6.5）。今回充填した doc のみ現内容ハッシュ、持ち越しは前回値を
    #    引き継ぐ（errored-updated の stale 固定を防ぐ / Issue #22 レビュー対応）。
    new_checksums = compute_checksums_for_docs(
        docs, project_root, completed_paths=set(completed.keys()), prev_checksums=prev_checksums
    )
    if not write_checksums_yaml(
        new_checksums, checksums_file, header_comment=f"ToC checksums for key: {key}"
    ):
        warnings.append("failed to write checksums file")

    if not clean_work_dir(store_dir):
        warnings.append("failed to clean .toc_work")

    # 成功後にバックアップを除去
    remove_backup(backup_path)

    log(
        f"merge: added={counts['added']} updated={counts['updated']} "
        f"deleted={counts['deleted']} unchanged={counts['unchanged']} "
        f"file_count={len(docs)}"
    )

    # 6. AI 抽出だった対象の集約（DES-008 §8.2 の書き戻し候補 / 報告用の出力のみ）。
    #    ToC の生成完了後に SKILL がユーザへ提示するための一時情報であり、
    #    toc.yaml にも checksums にも書き出さない。最終 docs に残っている path に
    #    限る（削除された path は書き戻し先が存在しないため候補にならない）。
    ai_extracted_paths = sorted(
        path for path, extracted_by in provenance.items()
        if extracted_by == EXTRACTED_BY_AI and path in docs
    )

    return True, {
        "error_code": None,
        "counts": counts,
        "deleted_paths": deleted,
        "warnings": warnings,
        "ai_extracted_paths": ai_extracted_paths,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv=None):
    """コマンドライン引数を解析する。"""
    parser = argparse.ArgumentParser(
        description="Merge completed pending YAML entries into toc.yaml (key + path I/F)"
    )
    parser.add_argument("--key", help="User-specified key (opaque)")
    parser.add_argument(
        "--all", action="store_true",
        help="Single mode: target reserved key 'all' (same as omitting --key)",
    )
    parser.add_argument(
        "--delete-only", action="store_true",
        help="Apply deletions only (do not merge .toc_work/ pendings)",
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    project_root = get_project_root()

    # 1. key 解決（--all / --key 省略 → 予約 all、--key all → KEY_RESERVED）
    try:
        key = resolve_key_from_args(args)
    except KeyError_ as e:
        emit_json(STATUS_ERROR, error_code=e.error_code, message=str(e))
        return 1

    store_dir = resolve_store_dir(key, project_root)
    toc_rel = toc_path_rel(store_dir, project_root)
    toc_path = store_dir / TOC_FILENAME

    # delete-only で toc.yaml が存在しないのはエラー（削除対象が無い）
    if args.delete_only and not toc_path.exists():
        emit_json(
            STATUS_ERROR,
            error_code=ErrorCode.TOC_NOT_FOUND,
            message=f"toc.yaml not found for delete-only: {toc_rel}",
            key=key,
            toc_path=toc_rel,
        )
        return 1

    # 通常 merge で work dir も既存 toc も無ければ統合対象が無い。
    # ただし prepare が「desired 0 件（空 repo / 対象 0 件）」を検出して空意図サイドカーを
    # 残していれば、それは「空 ToC を冪等出力すべき」意図（DES-005 §9.2 / §9.3 /
    # REQ-001 NFR-N05 / 受け入れ基準）であり、NO_TARGETS にせず空 toc.yaml を出力する。
    # 空意図サイドカーが無い（= prepare 未実行で何も準備されていない）場合のみ NO_TARGETS。
    work_dir = store_dir / WORK_DIRNAME
    if not args.delete_only:
        has_pending = work_dir.exists() and any(
            f for f in work_dir.glob("*.yaml") if not f.name.startswith(".")
        )
        has_empty_intent = (work_dir / EMPTY_INTENT_SIDECAR_FILENAME).exists()
        if not has_pending and not toc_path.exists() and not has_empty_intent:
            emit_json(
                STATUS_ERROR,
                error_code=ErrorCode.NO_TARGETS,
                message="no pending entries and no existing toc.yaml to merge",
                key=key,
                toc_path=toc_rel,
            )
            return 1

    ok, payload = run_merge(
        store_dir, key, project_root, delete_only=args.delete_only
    )

    status = STATUS_OK if ok else STATUS_ERROR
    # ai_extracted_paths は merge 成功時のみ出力する（DES-008 §8.2 は「ToC の
    # 生成完了後に提示」と規定するため、ロールバック経路では候補を出さない）。
    extra = None
    if "ai_extracted_paths" in payload:
        extra = {"ai_extracted_paths": payload["ai_extracted_paths"]}
    emit_json(
        status,
        error_code=payload.get("error_code"),
        message=payload.get("message"),
        key=key,
        toc_path=toc_rel,
        counts=payload.get("counts"),
        warnings=payload.get("warnings"),
        deleted_paths=payload.get("deleted_paths"),
        extra=extra,
    )
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
