#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
get_toc.py — ToC 取得・抽出（doc-advisor plugin / key + path I/F）

DES-005 §4.1（モジュール）/ §7（ToC スキーマ）/ §8（JSON 出力契約）/
§11.2（検索ユースケースのシーケンス）を実装する。
旧 filter_toc.py の paths 抽出機能を本 script に統合・新設する。

責務（決定的処理。lexical ranking / score 付けはしない / FR-N05-2）:
- key 解決（予約 key all / 任意 all reject。toc_store.resolve_key_from_args を使う）
- store_dir/toc.yaml の取得（load_existing_toc）。不在は TOC_NOT_FOUND
- --paths 指定時は一致する docs エントリのみ縮小抽出
- ToC の定義順を保持し、score / rank フィールドを持たせない（FR-N05-2）
- JSON 出力（toc_store.emit_json）または YAML 出力（検索 SKILL が AI に渡す用途）

CLI:
    python3 get_toc.py --key <key>
    python3 get_toc.py --all
    python3 get_toc.py --key <key> --paths "docs/a.md,docs/b.md"
    python3 get_toc.py --key <key> --format yaml

標準ライブラリのみ使用（NFR-N01）。
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from toc_utils import (
    get_project_root,
    normalize_path,
    load_existing_toc,
    yaml_escape,
)
from toc_store import (
    ErrorCode,
    KeyError_,
    STATUS_OK,
    STATUS_ERROR,
    resolve_store_dir,
    resolve_key_from_args,
    emit_json,
    toc_path_rel,
)

# ---------------------------------------------------------------------------
# 定数
# ---------------------------------------------------------------------------

# toc.yaml ファイル名
TOC_FILENAME = "toc.yaml"

# ToC エントリのフィールド描画順（DES-005 §7.1: doc_type を除去）。
# score / rank は持たない（FR-N05-2）。
SCALAR_FIELDS = ("title", "purpose")
LIST_FIELDS = ("content_details", "applicable_tasks", "keywords")


# ---------------------------------------------------------------------------
# 縮小抽出（旧 filter_toc.render_subset_yaml 相当 / FR-N05-1）
# ---------------------------------------------------------------------------

def filter_docs_by_paths(docs, requested_paths):
    """docs から requested_paths に一致するエントリのみを抽出する。

    ToC の定義順を保持する（FR-N05-2）。requested_paths の指定順ではなく、
    docs（= toc.yaml の定義順）の出現順に従う。

    Args:
        docs: source_file -> entry の dict（load_existing_toc の戻り値。
              Python 3.7+ の dict は挿入順 = toc.yaml の定義順を保持する）
        requested_paths: 正規化済み・重複除去済みの要求 path リスト

    Returns:
        tuple: (filtered, missing)
            filtered: 抽出された source_file -> entry の dict（定義順保持）
            missing: ToC に存在しなかった要求 path（要求順）のリスト
    """
    requested_set = set(requested_paths)
    filtered = {
        source_file: entry
        for source_file, entry in docs.items()
        if source_file in requested_set
    }
    missing = [p for p in requested_paths if p not in docs]
    return filtered, missing


# ---------------------------------------------------------------------------
# YAML 出力（検索 SKILL が AI に渡す用途 / DES-005 §7.1 スキーマ）
# ---------------------------------------------------------------------------

def render_toc_yaml(docs, *, key, toc_rel, full_count):
    """docs を YAML 文字列として描画する（DES-005 §7.1: doc_type 除去）。

    ToC の定義順を保持する（docs の挿入順をそのまま使う。sorted しない）。
    score / rank フィールドは描画しない（FR-N05-2）。

    Args:
        docs: source_file -> entry の dict（描画対象。定義順保持）
        key: original key（metadata.key に転記）
        toc_rel: toc.yaml の project-relative パス（ヘッダ表示用）
        full_count: 元 ToC の総エントリ数（縮小抽出の統計用）

    Returns:
        str: YAML 文字列（末尾改行付き）
    """
    lines = []
    lines.append(f"# Subset/View of {toc_rel}")
    lines.append(
        f"# Generated by get_toc.py at "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}"
    )
    lines.append("")

    lines.append("metadata:")
    lines.append(f"  key: {yaml_escape(key)}")
    lines.append(f"  file_count: {len(docs)}")
    lines.append(f"  full_count: {full_count}")
    lines.append("")

    lines.append("docs:")
    if not docs:
        lines.append("  {}")
    else:
        for source_file, entry in docs.items():
            lines.append(f"  {yaml_escape(source_file)}:")
            for field in SCALAR_FIELDS:
                if field in entry and entry[field] is not None:
                    lines.append(f"    {field}: {yaml_escape(entry[field])}")
            for field in LIST_FIELDS:
                if field in entry and entry[field]:
                    lines.append(f"    {field}:")
                    for item in entry[field]:
                        lines.append(f"      - {yaml_escape(item)}")

    return "\n".join(lines) + "\n"


def build_docs_payload(docs):
    """JSON 出力用に docs を整形する（DES-005 §7.1: doc_type 除去）。

    ToC の定義順を保持する（dict 挿入順）。score / rank フィールドは持たせない。
    title/purpose と 3 配列のみを既定順に整形した dict を返す。

    Args:
        docs: source_file -> entry の dict（定義順保持）

    Returns:
        dict: source_file -> {title, purpose, content_details, ...} の dict
    """
    payload = {}
    for source_file, entry in docs.items():
        clean = {}
        for field in SCALAR_FIELDS:
            if field in entry and entry[field] is not None:
                clean[field] = entry[field]
        for field in LIST_FIELDS:
            if field in entry and entry[field]:
                clean[field] = list(entry[field])
        payload[source_file] = clean
    return payload


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv=None):
    """コマンドライン引数を解析する。"""
    parser = argparse.ArgumentParser(
        description="Get/extract ToC for a key (full or --paths subset). No ranking."
    )
    parser.add_argument("--key", help="User-specified key (opaque)")
    parser.add_argument(
        "--all", action="store_true",
        help="Single mode: target reserved key 'all'",
    )
    parser.add_argument(
        "--paths",
        help="Comma-separated project-root-relative paths to extract (subset)",
    )
    parser.add_argument(
        "--format", choices=["json", "yaml"], default="json",
        help="Output format. json (default) emits the JSON contract; "
             "yaml emits ToC YAML for AI consumption.",
    )
    return parser.parse_args(argv)


def parse_paths_arg(raw):
    """--paths（カンマ区切り）を正規化・重複除去して返す（初出順保持）。

    Args:
        raw: --paths の生文字列（None の場合は全体取得）

    Returns:
        list[str] | None: 正規化済み path リスト。--paths 未指定時は None
    """
    if raw is None:
        return None
    normalized = []
    seen = set()
    for token in raw.split(","):
        token = token.strip()
        if not token:
            continue
        norm = normalize_path(token)
        if norm in seen:
            continue
        seen.add(norm)
        normalized.append(norm)
    return normalized


def main(argv=None):
    args = parse_args(argv)
    project_root = get_project_root()

    # 1. key 解決（--all / --key 省略 → 予約 all、--key all → KEY_RESERVED）
    try:
        key = resolve_key_from_args(args)
    except KeyError_ as e:
        emit_json(STATUS_ERROR, error_code=e.error_code, message=str(e))
        return 1

    store_dir = resolve_store_dir(key, project_root)
    toc_path = store_dir / TOC_FILENAME
    toc_rel = toc_path_rel(store_dir, project_root)

    # 2. toc.yaml の取得（不在は TOC_NOT_FOUND）
    if not toc_path.exists():
        emit_json(
            STATUS_ERROR,
            error_code=ErrorCode.TOC_NOT_FOUND,
            message=f"ToC not found for key: {key} ({toc_rel})",
            key=key,
            toc_path=toc_rel,
        )
        return 1

    # load_existing_toc は dict（挿入順 = toc.yaml の定義順）を返す（FR-N05-2）
    docs = load_existing_toc(toc_path)
    full_count = len(docs)

    # 3. --paths 縮小抽出（ranking / score なし。定義順保持）
    requested_paths = parse_paths_arg(args.paths)
    if requested_paths is not None:
        docs, missing = filter_docs_by_paths(docs, requested_paths)
    else:
        missing = []

    # 4. 出力（両形式とも定義順保持・score/rank なし）
    if args.format == "yaml":
        # 検索 SKILL が AI に渡す用途。YAML 本体を stdout に出す。
        sys.stdout.write(
            render_toc_yaml(docs, key=key, toc_rel=toc_rel, full_count=full_count)
        )
        return 0

    # JSON 出力（FR-N08 契約: status / error_code 必須）。
    payload = {
        "status": STATUS_OK,
        "error_code": None,
        "key": key,
        "toc_path": toc_rel,
        "docs": build_docs_payload(docs),
        "file_count": len(docs),
        "full_count": full_count,
    }
    if requested_paths is not None:
        payload["normalized_paths"] = requested_paths
        payload["missing_paths"] = missing
    sys.stdout.write(json.dumps(payload, ensure_ascii=False))
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
